/**
 * ISO 3166-1 reference countries for AeroJudge (alpha-3 + alpha-2 + English name).
 * Upserted by seed — safe to re-run on live to add missing rows.
 */
export const COUNTRIES = [
  { code: 'AFG', code2: 'AF', name: 'Afghanistan' },
  { code: 'ALB', code2: 'AL', name: 'Albania' },
  { code: 'DZA', code2: 'DZ', name: 'Algeria' },
  { code: 'AND', code2: 'AD', name: 'Andorra' },
  { code: 'AGO', code2: 'AO', name: 'Angola' },
  { code: 'ATG', code2: 'AG', name: 'Antigua and Barbuda' },
  { code: 'ARG', code2: 'AR', name: 'Argentina' },
  { code: 'ARM', code2: 'AM', name: 'Armenia' },
  { code: 'AUS', code2: 'AU', name: 'Australia' },
  { code: 'AUT', code2: 'AT', name: 'Austria' },
  { code: 'AZE', code2: 'AZ', name: 'Azerbaijan' },
  { code: 'BHS', code2: 'BS', name: 'Bahamas' },
  { code: 'BHR', code2: 'BH', name: 'Bahrain' },
  { code: 'BGD', code2: 'BD', name: 'Bangladesh' },
  { code: 'BRB', code2: 'BB', name: 'Barbados' },
  { code: 'BLR', code2: 'BY', name: 'Belarus' },
  { code: 'BEL', code2: 'BE', name: 'Belgium' },
  { code: 'BLZ', code2: 'BZ', name: 'Belize' },
  { code: 'BEN', code2: 'BJ', name: 'Benin' },
  { code: 'BTN', code2: 'BT', name: 'Bhutan' },
  { code: 'BOL', code2: 'BO', name: 'Bolivia' },
  { code: 'BIH', code2: 'BA', name: 'Bosnia and Herzegovina' },
  { code: 'BWA', code2: 'BW', name: 'Botswana' },
  { code: 'BRA', code2: 'BR', name: 'Brazil' },
  { code: 'BRN', code2: 'BN', name: 'Brunei' },
  { code: 'BGR', code2: 'BG', name: 'Bulgaria' },
  { code: 'BFA', code2: 'BF', name: 'Burkina Faso' },
  { code: 'BDI', code2: 'BI', name: 'Burundi' },
  { code: 'CPV', code2: 'CV', name: 'Cabo Verde' },
  { code: 'KHM', code2: 'KH', name: 'Cambodia' },
  { code: 'CMR', code2: 'CM', name: 'Cameroon' },
  { code: 'CAN', code2: 'CA', name: 'Canada' },
  { code: 'CAF', code2: 'CF', name: 'Central African Republic' },
  { code: 'TCD', code2: 'TD', name: 'Chad' },
  { code: 'CHL', code2: 'CL', name: 'Chile' },
  { code: 'CHN', code2: 'CN', name: 'China' },
  { code: 'COL', code2: 'CO', name: 'Colombia' },
  { code: 'COM', code2: 'KM', name: 'Comoros' },
  { code: 'COG', code2: 'CG', name: 'Congo' },
  { code: 'COD', code2: 'CD', name: 'Congo (Democratic Republic)' },
  { code: 'CRI', code2: 'CR', name: 'Costa Rica' },
  { code: 'CIV', code2: 'CI', name: "Côte d'Ivoire" },
  { code: 'HRV', code2: 'HR', name: 'Croatia' },
  { code: 'CUB', code2: 'CU', name: 'Cuba' },
  { code: 'CYP', code2: 'CY', name: 'Cyprus' },
  { code: 'CZE', code2: 'CZ', name: 'Czechia' },
  { code: 'DNK', code2: 'DK', name: 'Denmark' },
  { code: 'DJI', code2: 'DJ', name: 'Djibouti' },
  { code: 'DMA', code2: 'DM', name: 'Dominica' },
  { code: 'DOM', code2: 'DO', name: 'Dominican Republic' },
  { code: 'ECU', code2: 'EC', name: 'Ecuador' },
  { code: 'EGY', code2: 'EG', name: 'Egypt' },
  { code: 'SLV', code2: 'SV', name: 'El Salvador' },
  { code: 'GNQ', code2: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ERI', code2: 'ER', name: 'Eritrea' },
  { code: 'EST', code2: 'EE', name: 'Estonia' },
  { code: 'SWZ', code2: 'SZ', name: 'Eswatini' },
  { code: 'ETH', code2: 'ET', name: 'Ethiopia' },
  { code: 'FJI', code2: 'FJ', name: 'Fiji' },
  { code: 'FIN', code2: 'FI', name: 'Finland' },
  { code: 'FRA', code2: 'FR', name: 'France' },
  { code: 'GAB', code2: 'GA', name: 'Gabon' },
  { code: 'GMB', code2: 'GM', name: 'Gambia' },
  { code: 'GEO', code2: 'GE', name: 'Georgia' },
  { code: 'DEU', code2: 'DE', name: 'Germany' },
  { code: 'GHA', code2: 'GH', name: 'Ghana' },
  { code: 'GRC', code2: 'GR', name: 'Greece' },
  { code: 'GRD', code2: 'GD', name: 'Grenada' },
  { code: 'GTM', code2: 'GT', name: 'Guatemala' },
  { code: 'GIN', code2: 'GN', name: 'Guinea' },
  { code: 'GNB', code2: 'GW', name: 'Guinea-Bissau' },
  { code: 'GUY', code2: 'GY', name: 'Guyana' },
  { code: 'HTI', code2: 'HT', name: 'Haiti' },
  { code: 'HND', code2: 'HN', name: 'Honduras' },
  { code: 'HUN', code2: 'HU', name: 'Hungary' },
  { code: 'ISL', code2: 'IS', name: 'Iceland' },
  { code: 'IND', code2: 'IN', name: 'India' },
  { code: 'IDN', code2: 'ID', name: 'Indonesia' },
  { code: 'IRN', code2: 'IR', name: 'Iran' },
  { code: 'IRQ', code2: 'IQ', name: 'Iraq' },
  { code: 'IRL', code2: 'IE', name: 'Ireland' },
  { code: 'ISR', code2: 'IL', name: 'Israel' },
  { code: 'ITA', code2: 'IT', name: 'Italy' },
  { code: 'JAM', code2: 'JM', name: 'Jamaica' },
  { code: 'JPN', code2: 'JP', name: 'Japan' },
  { code: 'JOR', code2: 'JO', name: 'Jordan' },
  { code: 'KAZ', code2: 'KZ', name: 'Kazakhstan' },
  { code: 'KEN', code2: 'KE', name: 'Kenya' },
  { code: 'KIR', code2: 'KI', name: 'Kiribati' },
  { code: 'PRK', code2: 'KP', name: 'Korea (North)' },
  { code: 'KOR', code2: 'KR', name: 'Korea (South)' },
  { code: 'KWT', code2: 'KW', name: 'Kuwait' },
  { code: 'KGZ', code2: 'KG', name: 'Kyrgyzstan' },
  { code: 'LAO', code2: 'LA', name: 'Laos' },
  { code: 'LVA', code2: 'LV', name: 'Latvia' },
  { code: 'LBN', code2: 'LB', name: 'Lebanon' },
  { code: 'LSO', code2: 'LS', name: 'Lesotho' },
  { code: 'LBR', code2: 'LR', name: 'Liberia' },
  { code: 'LBY', code2: 'LY', name: 'Libya' },
  { code: 'LIE', code2: 'LI', name: 'Liechtenstein' },
  { code: 'LTU', code2: 'LT', name: 'Lithuania' },
  { code: 'LUX', code2: 'LU', name: 'Luxembourg' },
  { code: 'MDG', code2: 'MG', name: 'Madagascar' },
  { code: 'MWI', code2: 'MW', name: 'Malawi' },
  { code: 'MYS', code2: 'MY', name: 'Malaysia' },
  { code: 'MDV', code2: 'MV', name: 'Maldives' },
  { code: 'MLI', code2: 'ML', name: 'Mali' },
  { code: 'MLT', code2: 'MT', name: 'Malta' },
  { code: 'MHL', code2: 'MH', name: 'Marshall Islands' },
  { code: 'MRT', code2: 'MR', name: 'Mauritania' },
  { code: 'MUS', code2: 'MU', name: 'Mauritius' },
  { code: 'MEX', code2: 'MX', name: 'Mexico' },
  { code: 'FSM', code2: 'FM', name: 'Micronesia' },
  { code: 'MDA', code2: 'MD', name: 'Moldova' },
  { code: 'MCO', code2: 'MC', name: 'Monaco' },
  { code: 'MNG', code2: 'MN', name: 'Mongolia' },
  { code: 'MNE', code2: 'ME', name: 'Montenegro' },
  { code: 'MAR', code2: 'MA', name: 'Morocco' },
  { code: 'MOZ', code2: 'MZ', name: 'Mozambique' },
  { code: 'MMR', code2: 'MM', name: 'Myanmar' },
  { code: 'NAM', code2: 'NA', name: 'Namibia' },
  { code: 'NRU', code2: 'NR', name: 'Nauru' },
  { code: 'NPL', code2: 'NP', name: 'Nepal' },
  { code: 'NLD', code2: 'NL', name: 'Netherlands' },
  { code: 'NZL', code2: 'NZ', name: 'New Zealand' },
  { code: 'NIC', code2: 'NI', name: 'Nicaragua' },
  { code: 'NER', code2: 'NE', name: 'Niger' },
  { code: 'NGA', code2: 'NG', name: 'Nigeria' },
  { code: 'MKD', code2: 'MK', name: 'North Macedonia' },
  { code: 'NOR', code2: 'NO', name: 'Norway' },
  { code: 'OMN', code2: 'OM', name: 'Oman' },
  { code: 'PAK', code2: 'PK', name: 'Pakistan' },
  { code: 'PLW', code2: 'PW', name: 'Palau' },
  { code: 'PAN', code2: 'PA', name: 'Panama' },
  { code: 'PNG', code2: 'PG', name: 'Papua New Guinea' },
  { code: 'PRY', code2: 'PY', name: 'Paraguay' },
  { code: 'PER', code2: 'PE', name: 'Peru' },
  { code: 'PHL', code2: 'PH', name: 'Philippines' },
  { code: 'POL', code2: 'PL', name: 'Poland' },
  { code: 'PRT', code2: 'PT', name: 'Portugal' },
  { code: 'QAT', code2: 'QA', name: 'Qatar' },
  { code: 'ROU', code2: 'RO', name: 'Romania' },
  { code: 'RUS', code2: 'RU', name: 'Russia' },
  { code: 'RWA', code2: 'RW', name: 'Rwanda' },
  { code: 'KNA', code2: 'KN', name: 'Saint Kitts and Nevis' },
  { code: 'LCA', code2: 'LC', name: 'Saint Lucia' },
  { code: 'VCT', code2: 'VC', name: 'Saint Vincent and the Grenadines' },
  { code: 'WSM', code2: 'WS', name: 'Samoa' },
  { code: 'SMR', code2: 'SM', name: 'San Marino' },
  { code: 'STP', code2: 'ST', name: 'Sao Tome and Principe' },
  { code: 'SAU', code2: 'SA', name: 'Saudi Arabia' },
  { code: 'SEN', code2: 'SN', name: 'Senegal' },
  { code: 'SRB', code2: 'RS', name: 'Serbia' },
  { code: 'SYC', code2: 'SC', name: 'Seychelles' },
  { code: 'SLE', code2: 'SL', name: 'Sierra Leone' },
  { code: 'SGP', code2: 'SG', name: 'Singapore' },
  { code: 'SVK', code2: 'SK', name: 'Slovakia' },
  { code: 'SVN', code2: 'SI', name: 'Slovenia' },
  { code: 'SLB', code2: 'SB', name: 'Solomon Islands' },
  { code: 'SOM', code2: 'SO', name: 'Somalia' },
  { code: 'ZAF', code2: 'ZA', name: 'South Africa' },
  { code: 'SSD', code2: 'SS', name: 'South Sudan' },
  { code: 'ESP', code2: 'ES', name: 'Spain' },
  { code: 'LKA', code2: 'LK', name: 'Sri Lanka' },
  { code: 'SDN', code2: 'SD', name: 'Sudan' },
  { code: 'SUR', code2: 'SR', name: 'Suriname' },
  { code: 'SWE', code2: 'SE', name: 'Sweden' },
  { code: 'CHE', code2: 'CH', name: 'Switzerland' },
  { code: 'SYR', code2: 'SY', name: 'Syria' },
  { code: 'TWN', code2: 'TW', name: 'Taiwan' },
  { code: 'TJK', code2: 'TJ', name: 'Tajikistan' },
  { code: 'TZA', code2: 'TZ', name: 'Tanzania' },
  { code: 'THA', code2: 'TH', name: 'Thailand' },
  { code: 'TLS', code2: 'TL', name: 'Timor-Leste' },
  { code: 'TGO', code2: 'TG', name: 'Togo' },
  { code: 'TON', code2: 'TO', name: 'Tonga' },
  { code: 'TTO', code2: 'TT', name: 'Trinidad and Tobago' },
  { code: 'TUN', code2: 'TN', name: 'Tunisia' },
  { code: 'TUR', code2: 'TR', name: 'Türkiye' },
  { code: 'TKM', code2: 'TM', name: 'Turkmenistan' },
  { code: 'TUV', code2: 'TV', name: 'Tuvalu' },
  { code: 'UGA', code2: 'UG', name: 'Uganda' },
  { code: 'UKR', code2: 'UA', name: 'Ukraine' },
  { code: 'ARE', code2: 'AE', name: 'United Arab Emirates' },
  { code: 'GBR', code2: 'GB', name: 'United Kingdom' },
  { code: 'USA', code2: 'US', name: 'United States' },
  { code: 'URY', code2: 'UY', name: 'Uruguay' },
  { code: 'UZB', code2: 'UZ', name: 'Uzbekistan' },
  { code: 'VUT', code2: 'VU', name: 'Vanuatu' },
  { code: 'VAT', code2: 'VA', name: 'Vatican City' },
  { code: 'VEN', code2: 'VE', name: 'Venezuela' },
  { code: 'VNM', code2: 'VN', name: 'Vietnam' },
  { code: 'YEM', code2: 'YE', name: 'Yemen' },
  { code: 'ZMB', code2: 'ZM', name: 'Zambia' },
  { code: 'ZWE', code2: 'ZW', name: 'Zimbabwe' },
] as const;

export type SeedCountry = (typeof COUNTRIES)[number];
